#!/usr/bin/bash

lib1="/home/user/SOURCE/openssl/src/openssl-3.4.1/libcrypto.so.3"
lib2="/home/user/SOURCE/openssl/src/openssl-3.4.1/libssl.so.3"
exe="./target/debug/client2"
set -xe
cargo build
ls -la -- "${lib1}" "${lib2}" "$exe"
export LD_PRELOAD="${lib1}:${lib2}"
ldd -- "$exe"
time "$exe" "$@"

