#!/usr/bin/bash

read -rp "This overwrites/unpacks the source again, and doesn't build! Continue? (only \"yes\" will) " answer

if [[ "$answer" == "yes" ]]; then
    echo "Continuing..."
    # Insert code for when the answer is "yes"
elif [[ "$answer" == "no" ]]; then
    echo "Aborting..."
    exit 1
else
    echo "Invalid input. Please type exactly 'yes' or 'no', case sensitive."
    exit 1
fi

time makepkg --nobuild --nocheck --skippgpcheck --noarchive
#--noprepare
echo "remember that 'confeeg' must be in build() on first run, and not in prepare() else CFLAGS etc. wont be used from /etc/makepkg.conf, and running it only once is enough, until next time the src/openssl-3.4.1 dir gets remade/extracted."

