#!/usr/bin/bash

#lib1=~/"SOURCE/openssl/src/openssl-3.4.1/libcrypto.so.3"
#lib2=~/"SOURCE/openssl/src/openssl-3.4.1/libssl.so.3"
set -ex
source ../../env.sh
LD_PRELOAD="${lib1}:${lib2}" ./client "$@"

